### ISSUE TITLE
Nix cleanup

### ISSUE THREAD

**Issue by chreekat** [databrary/databrary#356]
# Clean the build
### Phase 1: easy wins

* [ ] databrary.nix should be precisely the output of cabal2nix.
  Overrides should be specified in default.nix
* [ ] Packages pinned at particular versions (like hjsonchema and its
  deps) should be pulled in as overlays
* [ ] Overlays should also be used for dontCheck/doJailbreak.
* [ ] Using so much doJailbreak is really questionable: look into it
* [ ] Make the cracklib dict a derivation and a build input
* [ ] Make solr a derivation and a build input
    * It's already on nixpkgs, albeit at an older version (easily
      fixed)
    * [ ] Remove service management from the app

### Phase 2: some unknowns and external dependencies
* [ ] Pin nixpkgs for all components and dev tools
    * Causes a huge rebuild since the node deps aren't cached.
* [ ] Make node_modules a derivation and a build input
* [x] Drop dependency on reflex-platform
* [ ] Set up and configure a binary cache
* [ ] store/ and databrary_logs/ should most likely be created at runtime

Note: I don't mind gargoyle, except that it's only a prototype (no
docs, no instructions). A project serving an identical purpose (but
with its own pros and cons) is
[sdb.hs](https://git.snowdrift.coop/sd/snowdrift/blob/master/sdb.hs)
Having briefly reread sdb.hs, I think I could fix some of the
outstanding problems in an hour or two, so I might break it out and
reuse it here. (I could also just reimplement it in a Makefile!)

# Clean the development environment (nix-shell and Make)
## Requirements
* Fast incremental builds for backend dev
* Fast incremental builds for frontend dev
* Use or emulate 'npm install', 'npm outdated', and 'npm update'

## Tasks
* [ ] Manage the database behind the scenes
* [ ] Experiment with ghcid
* [ ] Document when and how to reload static assets
* [ ] Experiment with using multiple tools at once: conceivably
  ghci(run) + ghci(test) + ghcid + vim errorlist population

**Comment by chreekat** [comment]
Initial fumblings cause linux-util to be built twice with different nixpkgs, for unknown reasons. It's actually possible this was happening all along. I'm diving deeper.
